In [2]:
import numpy as np
import gym 
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

In [4]:
#q-table initialization
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [9]:
rewards_all_episodes = []

#Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0;
    
    for step in range(max_steps_per_episode):
        
        #Exploration-Exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s,a)
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
    
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
        #Exploration rate decay
        exploration_rate = min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        
        rewards_all_episodes.append(rewards_current_episode)


#Calculate and print average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("-------------Average rewards per thousand episodes-------------\n")
for r in rewards_per_thousand_episodes:
    print(count,": ", str(sum(r/1000)))
    count+=1000

#Print updated Q-table
print("\n\n----------------Q_table----------------\n")
print(q_table)

-------------Average reqrds per thousand episodes-------------

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0


----------------Q_table----------------

[[0.54124033 0.52421249 0.5266282  0.51200149]
 [0.38537147 0.34499552 0.38214177 0.51556964]
 [0.43412323 0.43055668 0.3927865  0.49026384]
 [0.19121365 0.35057626 0.36758174 0.47542243]
 [0.55526029 0.28972546 0.31343752 0.41932534]
 [0.         0.         0.         0.        ]
 [0.17082375 0.08170835 0.28149909 0.21803364]
 [0.         0.         0.         0.        ]
 [0.4312491  0.5105299  0.38780821 0.59339515]
 [0.34035644 0.6226219  0.30879229 0.46638146]
 [0.60970989 0.41579912 0.37156113 0.34365151]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.44646632 0.51679841 0.69634656 0.43223298]
 [0.7230491  0.83998672 0.75494842 0.78197683]
 [0.         0.         0.         0.        ]]
