In [2]:
import numpy as np
import gym 
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

In [4]:
#q-table initialization
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.001


In [6]:
rewards_all_episodes = []

#Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0;
    
    for step in range(max_steps_per_episode):
        
        #Exploration-Exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s,a)
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
    
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)


#Calculate and print average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("-------------Average rewards per thousand episodes-------------\n")
for r in rewards_per_thousand_episodes:
    print(count,": ", str(sum(r/1000)))
    count+=1000

#Print updated Q-table
print("\n\n----------------Q_table----------------\n")
print(q_table)

-------------Average rewards per thousand episodes-------------

1000 :  0.03800000000000003
2000 :  0.19800000000000015
3000 :  0.4170000000000003
4000 :  0.5910000000000004
5000 :  0.6560000000000005
6000 :  0.6790000000000005
7000 :  0.7420000000000005
8000 :  0.7210000000000005
9000 :  0.7220000000000005
10000 :  0.7570000000000006


----------------Q_table----------------

[[0.5691454  0.47747625 0.48810327 0.48786736]
 [0.36352899 0.3155908  0.39492538 0.50662491]
 [0.39021721 0.41174114 0.39798023 0.47428712]
 [0.29436431 0.28937064 0.32701083 0.44768985]
 [0.59402741 0.34879514 0.474528   0.34423031]
 [0.         0.         0.         0.        ]
 [0.4534533  0.13390494 0.18778584 0.14656689]
 [0.         0.         0.         0.        ]
 [0.42255873 0.35609308 0.42731096 0.62083973]
 [0.42717961 0.67642942 0.47378821 0.38075097]
 [0.62722518 0.35661847 0.3816887  0.18580169]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5090

In [7]:
for episode in range(3):
    state = env.reset()
    done= False
    print("********EPISODE ", episode+1, "*******\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state,reward,done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!**")
                time.sleep(3)
            else:
                print("***You Fell through a hole*****")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()



  (Left)
SFFF
FHFH
FFFH
HFFG
***You Fell through a hole*****
