In [28]:
import numpy as np
import gym 
import random
import time
from IPython.display import clear_output

In [29]:
env = gym.make("FrozenLake-v1")

In [30]:
#q-table initialization
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.001


In [32]:
rewards_all_episodes = []

#Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0;
    
    for step in range(max_steps_per_episode):
        
        #Exploration-Exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
            
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s,a)
        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
    
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate-min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)


#Calculate and print average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("-------------Average rewards per thousand episodes-------------\n")
for r in rewards_per_thousand_episodes:
    print(count,": ", str(sum(r/1000)))
    count+=1000

#Print updated Q-table
print("\n\n----------------Q_table----------------\n")
print(q_table)

-------------Average rewards per thousand episodes-------------

1000 :  0.04300000000000003
2000 :  0.22200000000000017
3000 :  0.46500000000000036
4000 :  0.5730000000000004
5000 :  0.6900000000000005
6000 :  0.6900000000000005
7000 :  0.7030000000000005
8000 :  0.7010000000000005
9000 :  0.7430000000000005
10000 :  0.7520000000000006


----------------Q_table----------------

[[0.54029122 0.49179441 0.50361804 0.49501217]
 [0.33646809 0.30553868 0.26400997 0.5115799 ]
 [0.39400343 0.40124618 0.40623433 0.49432477]
 [0.31285815 0.25358371 0.27161543 0.48593879]
 [0.56459681 0.36429134 0.33190488 0.36964255]
 [0.         0.         0.         0.        ]
 [0.37453984 0.18159344 0.18371938 0.1542529 ]
 [0.         0.         0.         0.        ]
 [0.32292065 0.33485272 0.40418136 0.61785574]
 [0.32442481 0.64852031 0.35795671 0.41028403]
 [0.65363193 0.35953052 0.38033627 0.35427207]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.498

In [33]:
for episode in range(3):
    state = env.reset()
    done= False
    print("********EPISODE ", episode+1, "*******\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])
        new_state,reward,done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!**")
                time.sleep(3)
            else:
                print("***You Fell through a hole*****")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()



  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!**
